server:
  port: 9082
spring:
  redis:
    host: 47.105.34.102
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 10
  application:
    name: shop-index
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eurekaServerReadTimeoutSeconds: 10
    eurekaServerConnectTimeoutSeconds: 10




