
spring:
  application:
    name: login-web

  redis:
    host: 47.105.34.102
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 10

  rabbitmq:
    host: 47.105.34.102
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: qf1909

ribbon:
  ReadTimeout: 4000
  ConnectTimout: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080