
spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 47.105.34.102
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: qf1909
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8081