

spring:
  application:
    name: pay-server
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:com.qf.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true