spring:
  application:
    name: shop-search-web
server:
  port: 9084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eurekaServerReadTimeoutSeconds: 10
    eurekaServerConnectTimeoutSeconds: 10
