spring:
  application:
    name: shop-order-create-orderdetail-service
  rabbitmq:
    virtual-host: qf1909
    port: 5672
    username: rabbit
    password: 123456
    host: 47.105.34.102
#  redis:
#    host: 47.105.34.102
#    port: 6379
#    password: password
  redis:
    cluster:
      nodes: 47.111.235.107:6379,47.111.235.107:6380,47.111.235.107:6381,47.111.235.107:6382,47.111.235.107:6383,47.111.235.107:6384
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
