
spring:
  application:
    name: user-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.34.102/qf-v6
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


