spring:
  application:
    name: shop-product
server:
  port: 9086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-read-timeout-seconds: 10
    eureka-server-connect-timeout-seconds: 10
