server:
  port: 8088
spring:
  redis:
    host: 47.105.34.102
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 47.105.34.102
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: qf1909
  application:
    name: shop-order-service
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eurekaServerReadTimeoutSeconds: 10
    eurekaServerConnectTimeoutSeconds: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
