server:
  port: 8764

spring:
  application:
    name: product-order-service
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.105.34.102
    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


