server:
  port: 9085

spring:
  redis:
    host: 47.105.34.102
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 10
  application:
    name: shop-cart
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



