server:
  port: 9085

spring:
  application:
    name: product-search-service
  data:
    solr:
      host: http://47.105.34.102:8983/solr/ik_core
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
