server:
  port: 8763

spring:
  application:
    name: product-search-service
  data:
    solr:
      host: http://47.105.34.102:8983/solr/ik_core
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

imageServer: http://localhost:9084