spring:
  application:
    name: shop-search-service
  datasource:
    url: jdbc:mysql://47.105.34.102/qf-v6
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://47.105.34.102:8983/solr/ik_core

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-read-timeout-seconds: 10
    eureka-server-connect-timeout-seconds: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true