server:
  port: 9087
#spring:
#  redis:
#    host: 47.105.34.102
#    port: 6379
#    password: password
#    jedis:
#      pool:
#        max-active: 10
spring:
  redis:
    cluster:
      nodes: 47.111.235.107:6379,47.111.235.107:6380,47.111.235.107:6381,47.111.235.107:6382,47.111.235.107:6383,47.111.235.107:6384
  rabbitmq:
    host: 47.105.34.102
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: qf1909
  application:
    name: shop-order
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eurekaServerReadTimeoutSeconds: 10
    eurekaServerConnectTimeoutSeconds: 10