
server:
  port: 9084


spring:
  redis:
    host: 47.105.34.102
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 47.105.34.102
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: qf1909